# Changes here will be overwritten by Copier
_commit: 61fe43f
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: dev@1kbgz.com
github: 1kbgz
project_description: ETL Tools for ccflow
project_name: ccflow-etl
python_version_primary: '3.11'
team: 1kbgz
