# @package calendars

daily:
  _target_: ccflow_etl.DailyCalendar

hourly:
  _target_: ccflow_etl.HourlyCalendar

weekly:
  _target_: ccflow_etl.WeeklyCalendar

first_day_of_month:
  _target_: ccflow_etl.IntervalCalendar
  interval: 1MS

last_day_of_month:
  _target_: ccflow_etl.IntervalCalendar
  interval: 1ME

weekdays:
  _target_: ccflow_etl.WeekdayCalendar

business_daily:
  _target_: ccflow_etl.BusinessDayCalendar

monday_friday:
  _target_: ccflow_etl.MondayFridayCalendar