# @package credentials

none:
  _target_: ccflow_etl.NoCredentials

username_password:
  _target_: ccflow_etl.UsernamePasswordCredentials

api_token:
  _target_: ccflow_etl.APITokenCredentials

api_key_secret:
  _target_: ccflow_etl.APIKeySecretCredentials

oauth:
  _target_: ccflow_etl.OAuthCredentials