# @package credentials

none:
  _target_: ccflow_etl.NoCredentials
  name: null

username_password:
  _target_: ccflow_etl.UsernamePasswordCredentials
  name: null
  username: null
  password: null
  username_env: null
  password_env: null

api_token:
  _target_: ccflow_etl.APITokenCredentials
  name: null
  token: null
  token_env: null
  scheme: Bearer

api_key_secret:
  _target_: ccflow_etl.APIKeySecretCredentials
  name: null
  api_key: null
  secret_key: null
  api_key_env: null
  secret_key_env: null

oauth:
  _target_: ccflow_etl.OAuthCredentials
  name: null
  client_id: null
  client_secret: null
  client_id_env: null
  client_secret_env: null
  token_url: null
  access_token: null
  refresh_token: null
  scopes: []
  extra: {}
