# @package _global_

defaults:
  - _self_
  - credentials: default
  - cache: noop
  - checkpoint: noop
  - callable: local_write
  - optional backfill: null

model:
  _target_: ccflow_etl.LocalWriteModel

cli:
  model:
    _target_: ccflow.FlowOptions
    evaluator:
      _target_: ccflow.evaluators.MultiEvaluator
      evaluators:
        - _target_: ccflow.evaluators.GraphEvaluator
        - _target_: ccflow.evaluators.MemoryCacheEvaluator
        - _target_: ccflow.evaluators.LoggingEvaluator
    cacheable: true
