# @package _global_

defaults:
  - _self_
  - credentials: default
  - execution: default
  - cache: noop
  - utilities: default
  - backfills: default

model:
  _target_: ccflow_etl.LocalWriteModel

task: ${model}
callable: ${oc.select:backfill,/task}

cli:
  model:
    _target_: ccflow.FlowOptions
    evaluator:
      _target_: ccflow.evaluators.MultiEvaluator
      evaluators:
        - _target_: ccflow.evaluators.GraphEvaluator
        - _target_: ccflow.evaluators.MemoryCacheEvaluator
        - _target_: ccflow.evaluators.LoggingEvaluator
    cacheable: true
